export default [
  {
    id: 1,
    userName: 'BijouBelle',
    avatar: '',
    mail: 'Bij@gmail.com',
    category: 'Bijoux',
    slug: 'bijouxxx',
    firstName: 'Lola',
    lastName: 'Lilo',
    brand: 'Bijouxxx',
    phone: '0622853645',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: '',
    picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
  {
    id: 2,
    userName: 'Crochetos',
    avatar: '',
    mail: 'crochetos@gmail.com',
    category: 'Travaux d\'aiguille',
    slug: 'crochetos',
    firstName: 'Leeloo',
    lastName: 'DallasMultipass',
    brand: 'Crochetos',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: '',
    picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
  {
    id: 3,
    userName: 'Claire',
    avatar: '',
    mail: 'claire@gmail.com',
    category: 'Bijoux',
    slug: 'claire',
    firstName: 'Claire',
    lastName: 'Dubis',
    brand: 'Clair\'s',
    phone: '0621569871',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: '',
    picture: 'https://images.pexels.com/photos/5157293/pexels-photo-5157293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
  {
    id: 4,
    userName: 'Sophie',
    avatar: '',
    mail: 'sophiegala@gmail.com',
    category: 'Sculpture',
    slug: 'sophie-sculpture',
    firstName: 'sophie',
    lastName: 'Gala',
    brand: 'Sophie Sculpture',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: '',
    picture: 'https://images.pexels.com/photos/2491244/pexels-photo-2491244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
  },
  {
    id: 5,
    userName: 'MarieCouture',
    avatar: '',
    mail: 'mariecouture@gmail.com',
    category: 'Travaux d\'aiguille',
    slug: 'marie-couture',
    firstName: 'Marie',
    lastName: 'Francis',
    brand: 'MarieCouture',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: '',
    picture: 'https://images.pexels.com/photos/3771080/pexels-photo-3771080.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
];
