export default [
  {
    id: 1,
    userName: 'BijouBelle',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'Bij@gmail.com',
    category: 'Bijoux',
    slug: 'bijouxxx',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    firstName: 'Lola',
    lastName: 'Lilo',
    brand: 'Bijouxxx',
    phone: '0622853645',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    facebook: 'http://www.facebook.com',
    twitter: 'http://www.facebook.com',
    instagram: 'http://www.facebook.com',
    pinterest: 'http://www.facebook.com',
    linkedin: 'http://www.facebook.com',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [
      {
        id: 1,
        body: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, ma',
        publishedDate: '18/06/2021',
        user: {
          id: 2,
          pseudo: 'Crochetos',
          avatar: 'https://thispersondoesnotexist.com/image',
          mail: 'crochetos@gmail.com',
          category: 'Travaux d\'aiguille',
          slug: 'crochetos',
          firstName: 'Leeloo',
          lastName: 'DallasMultipass',
          brand: 'Crochetos',
          phone: '0622456985',
          description: 'blablablabla',
          facebook: 'http://www.facebook.com',
          twitter: '',
          instagram: '',
          pinterest: '',
          linkedin: '',
          website: 'http://www.facebook.com',
          pictures: [
            {
              id: 1,
              picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
            {
              id: 2,
              picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
            {
              id: 3,
              picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
          ],
        },
      },
    ],
  },
  {
    id: 2,
    userName: 'Crochetos',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'crochetos@gmail.com',
    category: 'Travaux d\'aiguille',
    slug: 'crochetos',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    firstName: 'Leeloo',
    lastName: 'DallasMultipass',
    brand: 'Crochetos',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: 'http://www.facebook.com',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 3,
    userName: 'Claire',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'claire@gmail.com',
    category: 'Bijoux',
    slug: 'claire',
    firstName: 'Claire',
    lastName: 'Dubis',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Clair\'s',
    phone: '0621569871',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/5157293/pexels-photo-5157293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 4,
    userName: 'Sophie',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'sophiegala@gmail.com',
    category: 'Sculpture',
    slug: 'sophie-sculpture',
    firstName: 'sophie',
    lastName: 'Gala',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Sophie Sculpture',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: 'http://www.facebook.com',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/2491244/pexels-photo-2491244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 5,
    userName: 'MarieCouture',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'mariecouture@gmail.com',
    category: 'Travaux d\'aiguille',
    slug: 'marie-couture',
    firstName: 'Marie',
    lastName: 'Francis',
    brand: 'MarieCouture',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/3771080/pexels-photo-3771080.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 6,
    userName: 'Maurice',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'maurice@gmail.com',
    category: 'Ebenisterie',
    slug: 'maurice-bois',
    firstName: 'Maurice',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    lastName: 'Dupont',
    brand: 'Maurice Bois',
    phone: '0456315845',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: 'http://www.facebook.com',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/5466151/pexels-photo-5466151.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 7,
    userName: 'Germaine',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'germaine@gmail.com',
    category: 'Peinture',
    slug: 'germaine-frechette',
    firstName: 'Germaine',
    lastName: 'Fréchette',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Peinture Fraîche',
    phone: '0192939226',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/1570779/pexels-photo-1570779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 8,
    userName: 'Germaine',
    avatar: 'https://thispersondoesnotexist.com/image',
    mail: 'germaine@gmail.com',
    category: 'Peinture',
    slug: 'germaine-frechette',
    firstName: 'Germaine',
    lastName: 'Fréchette',
    brand: 'Peinture Fraîche',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    phone: '0192939226',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        picture: 'https://images.pexels.com/photos/1570779/pexels-photo-1570779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
];

export const categories = [
  {
    id: 1,
    categoryName: 'Travaux d\'aiguille',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'travaux-aiguille',
    picture: 'https://images.pexels.com/photos/37631/sewing-thimble-pins-safety-pins-37631.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    creators: [
      {
        id: 5,
        userName: 'MarieCouture',
        avatar: '',
        mail: 'mariecouture@gmail.com',
        category: 'Travaux d\'aiguille',
        slug: 'marie-couture',
        firstName: 'Marie',
        lastName: 'Francis',
        brand: 'MarieCouture',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: '',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/3771080/pexels-photo-3771080.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
      {
        id: 2,
        userName: 'Crochetos',
        avatar: '',
        mail: 'crochetos@gmail.com',
        category: 'Travaux d\'aiguille',
        slug: 'crochetos',
        firstName: 'Leeloo',
        lastName: 'DallasMultipass',
        brand: 'Crochetos',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: 'http://www.facebook.com',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    categoryName: 'Bijoux',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'bijoux',
    picture: 'https://images.pexels.com/photos/5157363/pexels-photo-5157363.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    creators: [
      {
        id: 1,
        userName: 'BijouBelle',
        avatar: '',
        mail: 'Bij@gmail.com',
        category: 'Bijoux',
        slug: 'bijouxxx',
        firstName: 'Lola',
        lastName: 'Lilo',
        brand: 'Bijouxxx',
        phone: '0622853645',
        description: 'blablablabla',
        facebook: 'http://www.facebook.com',
        twitter: '',
        instagram: '',
        pinterest: '',
        linkedin: '',
        website: 'http://www.facebook.com',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
      {
        id: 3,
        userName: 'Claire',
        avatar: '',
        mail: 'claire@gmail.com',
        category: 'Bijoux',
        slug: 'claire',
        firstName: 'Claire',
        lastName: 'Dubis',
        brand: 'Clair\'s',
        phone: '0621569871',
        description: 'blablablabla',
        facebook: '',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: 'http://www.facebook.com',
        linkedin: '',
        website: '',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/5157293/pexels-photo-5157293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    categoryName: 'Sculpture',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'sculpture',
    picture: 'https://images.pexels.com/photos/6598660/pexels-photo-6598660.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    creators: [
      {
        id: 4,
        userName: 'Sophie',
        avatar: '',
        mail: 'sophiegala@gmail.com',
        category: 'Sculpture',
        slug: 'sophie-sculpture',
        firstName: 'sophie',
        lastName: 'Gala',
        brand: 'Sophie Sculpture',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: '',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/2491244/pexels-photo-2491244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    categoryName: 'Ebénisterie',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'ebenisterie',
    picture: 'https://images.pexels.com/photos/5466161/pexels-photo-5466161.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    creators: [
      {
        id: 6,
        userName: 'Maurice',
        avatar: '',
        mail: 'maurice@gmail.com',
        category: 'Ebenisterie',
        slug: 'maurice-bois',
        firstName: 'Maurice',
        lastName: 'Dupont',
        brand: 'Maurice Bois',
        phone: '0456315845',
        description: 'blablablabla',
        facebook: '',
        twitter: 'http://www.facebook.com',
        instagram: '',
        pinterest: 'http://www.facebook.com',
        linkedin: '',
        website: '',
        pictures: [
          {
            id: 1,
            picture: 'https://images.pexels.com/photos/5466151/pexels-photo-5466151.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            picture: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            picture: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    categoryName: 'Design textile',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'design-textile',
    picture: 'https://images.pexels.com/photos/365067/pexels-photo-365067.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
];

export const comments = [
  {
    id: 1,
    body: 'Super top ce créateur',
    publishedDate: '18/06/2021',
  },
];
